### PR TITLE
fix repl always return 0

### LINKED ISSUE #1277: train successfully, but no data in hive table
**Description**
train successfully, but no data in hive table

**Reproduction Steps**
```shell
#!/usr/bin/env bash

INPUT_SQL="select * from pre.sqlflow_test_data to TRAIN sqlflow_models.DNNClassifier WITH model.n_classes = 3,model.hidden_units = [10,20] COLUMN sepal_length,sepal_width,petal_length,petal_width LABEL class INTO pre.iris_dnn_model22;"
HADOOP_USER_NAME="xxx"
HADOOP_USER_PASSWORD="xxxx"
MR_QUEUE_NAME="xxxx"
DEFAULT_DATABASE="pre"
#hive server
DATA_STUDIO_HIVESERVER2_IP="xxxx"
DATA_STUDIO_HIVESERVER2_PORT="xxxx"
SQL_FILE="/tmp/flow.sql"

DATASOURCE="hive://${HADOOP_USER_NAME}:${HADOOP_USER_PASSWORD}@${DATA_STUDIO_HIVESERVER2_IP}:${DATA_STUDIO_HIVESERVER2_PORT}/${DEFAULT_DATABASE}?auth=PLAIN&session.mapreduce.job.queuename=${MR_QUEUE_NAME}&session.hive.exec.compress.intermediate=true&session.hive.auto.convert.join=true&session.hive.exec.parallel=true"
echo "datasource is ${DATASOURCE}"

echo "${INPUT_SQL}" > ${SQL_FILE}

~/go/bin/repl -f "${SQL_FILE}" --datasource="${DATASOURCE}"
```

**Screenshots**
image
image

**Environment (Please complete the following information):**
DiDi SQLFlow_snapshot_20191128_v0.5

### LINKED ISSUE #1317: repl save model failed
Reproduce:

``` bash
> repl -e "
SELECT *
FROM iris.train
TO PREDICT iris.predict.class
USING sqlflow_models.my_dnn_model;" --datasource="xxx"
```

Failed logs:

``` text
sqlflow> SELECT *
FROM iris.train
TO TRAIN DNNClassifier
WITH
model.n_classes = 3,
model.hidden_units = [10, 20]
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO sqlflow_models.my_dnn_model;
time="2019-12-03T08:49:30Z" level=info msg="sqlflowCmd: run locally" package=sql
Evaluation result: {'accuracy': 0.7090909, 'average_loss': 1.2289135, 'loss': 1.2289135, 'global_step': 110}

Done training

time="2019-12-03T08:49:39Z" level=error msg="runSQLProgram error: failed to open database: Expecting but cannot find :// in datasource " package=sql
+
+
```

### PR DESCRIPTION
**Pull request by Yancey0623**
fixed #1277 
fixed #1317 

related #1318

### CODE REVIEW

File: cmd/repl/repl.go [hunk 1]
```diff
@@ -81,15 +81,13 @@ func render(rsp interface{}, table *tablewriter.Table) bool {
 		table.Append(row)
 		isTable = true
 	case error:
-		if os.Getenv("SQLFLOW_log_dir") != "" { // To avoid printing duplicated error message to console
-			log.New(os.Stderr, "", 0).Printf("ERROR: %v\n", s)
```
Comment (shendiaomo) [inline cmd/repl/repl.go:85]: We'd better keep this check somewhere to avoid printing error message twice when logging to stderr.

File: pkg/sql/model.go [hunk 2]
```diff
@@ -86,7 +86,6 @@ func (m *model) saveDB(db *DB, table string, session *pb.Session) (e error) {
 	if e != nil {
 		return fmt.Errorf("cannot create sqlfs file %s: %v", table, e)
 	}
-	defer sqlf.Close()
```
Comment (shendiaomo) [inline pkg/sql/model.go]: How about `defer`ing with the new `Close` code in a lambda?

**Review by typhoonzero — DISMISSED** [review]
Please checkout @shendiaomo 's comments and fix them in next PR?

File: cmd/repl/repl.go (hunk 1 above)
Comment (Yancey0623) [reply cmd/repl/repl.go:85]: Maybe we can use `log.Fatalf` to exit if some errors.

File: pkg/sql/model.go (hunk 2 above)
Comment (Yancey0623) [reply pkg/sql/model.go]: I believe should check the error of `hiveWriter.Close`, I updated this PR follow https://www.joeshaw.org/dont-defer-close-on-writable-files/ that uses a safe way to close sqlfs.

File: cmd/repl/repl.go (hunk 1 above)
Comment (shendiaomo) [reply cmd/repl/repl.go:85]: `log.Fatalf` will terminate the program, that's no good for the interactive mode of REPL.

File: pkg/sql/model.go (hunk 2 above)
Comment (shendiaomo) [reply pkg/sql/model.go]: Is it safe if we call `hiveWriter.Close` twice?

**Review by typhoonzero — APPROVED** [review]
