### PR TITLE
fix repl input history navigation crash issue (#2050)

### LINKED ISSUE #2050: repl input history navigation ends up with a crash
**Description**
When I run sqlflow in repl mode, I use ctrl+p/n to navigate the input history, it ends up with a crash when I have some Chinese character in history. I'm using the latest version of code.

**Reproduction Steps**
1. start sqlflow in repl mode
2. intput SELECT * FROM iris.train where class like '中文1';
3. press `ctrl+p` twice

**Expected Behavior**
It should go back in my input history for 2 steps, or stop at the oldest one if we have only one input history

**Screenshots**
C9D9094F-8B9A-4D55-BA5F-47F73E9B5F76

**Environment (Please complete the following information):**
 - OS: macOS 10.15.3
 - Browser:
 - Version:

**Additional Note**

### PR DESCRIPTION
**Pull request by lhw362950217**
Fix https://github.com/sql-machine-learning/sqlflow/issues/2050

### CODE REVIEW

File: cmd/repl/prompt.go [hunk 1]
```diff
@@ -327,7 +326,7 @@ func (p *promptState) navigateHistory(origInput string, older bool, buf *prompt.
 		}
 	}
 	prompt.GoLineBeginning(buf)
-	buf.Delete(len(buf.Text()))
+	buf.Delete(len([]rune(buf.Text())))
```
Comment (shendiaomo) [inline cmd/repl/prompt.go:329]: Is it possible to add a unit test for this case?

Comment (lhw362950217) [reply cmd/repl/prompt.go:329]: Yes, I will add one.

**Review by shendiaomo — APPROVED** [review]
lgtm++
