### PR TITLE
Fix invalid explain result

### LINKED ISSUE #1549: inconsistencies about shap interpretation
During my testing, I found that in the latest image, the shap interpretation and the local interpretation show inconsistencies.
image

`the detail  file show in this zip file:`
[housing-analyze-test-1226.html.zip](https://github.com/sql-machine-learning/sqlflow/files/4002021/housing-analyze-test-1226.html.zip)

### PR DESCRIPTION
**Pull request by Yancey0623**
fixed #1549 
TODO: move `xgboost/template_analyze.go` to `python/sqlflow_submitter/xgboost/analyze.py` and add accurary test.

### CODE REVIEW

**Review by weiguoz — APPROVED** [review]
LGTM

File: pkg/sql/codegen/xgboost/template_analyze.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ from sqlflow_submitter.db import connect_with_data_source, db_generator
 shap.initjs()
 
 feature_field_meta = json.loads('''{{.FieldDescJSON}}''')
-feature_column_name = sorted([k["name"] for k in feature_field_meta])
+feature_column_name = [k["name"] for k in feature_field_meta]
```
Comment (typhoonzero) [inline pkg/sql/codegen/xgboost/template_analyze.go:41]: Maybe add some comments to ensure we won't change it back?
