### PR TITLE
bug fix: step failed if sql statement contain quotes

### LINKED ISSUE #1909: step failed if a sql statement contain validation field
The reproduced SQL:
``` sql
SELECT *
FROM alifin_jtest_dev.sqlflow_test_iris_train
TO TRAIN DNNClassifier
WITH
	model.n_classes = 3,
	model.hidden_units = [10, 20],
	validation.select = "SELECT * FROM alifin_jtest_dev.sqlflow_test_iris_train"
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO my_dnn_model;
```

step logs:

``` text
sqlflow>

SELECT *
FROM alifin_jtest_dev.sqlflow_test_iris_train
TO TRAIN DNNClassifier
WITH
model.n_classes = 3,
model.hidden_units = [10, 20],
validation.select = SELECT
2020/02/26 16:08:46 runSQLProgram error: syntax error: at (100 ~ 106)-th runes near "SELECT"
```

### PR DESCRIPTION
**Pull request by Yancey0623**
fixed #1909

### CODE REVIEW

File: pkg/sql/codegen/couler/template.go [hunk 1]
```diff
@@ -46,18 +46,20 @@ step_envs["{{$k}}"] = "{{$v}}"
 {{end}}
 
 couler.clean_workflow_after_seconds_finished({{.WorkflowTTL}})
+def escap_sql(original_sql):
```
Comment (typhoonzero) [inline pkg/sql/codegen/couler/template.go]: `escape_sql` ?

**Review by typhoonzero — APPROVED** [review]
