### PR TITLE
Making BoostedTreesClassifier training in the unit test more stable

### LINKED ISSUE #1682: CI fails on CaseTrainBoostedTreesEstimatorAndExplain
Reference build: https://travis-ci.com/sql-machine-learning/sqlflow/jobs/274151235
```
=== RUN   TestEnd2EndMySQL/CaseTrainBoostedTreesEstimatorAndExplain
2020/01/10 07:42:53 runSQLProgram error: failed: exit status 1
==========Program==========
import tensorflow as tf
from sqlflow_submitter.tensorflow import explain
from tensorflow.estimator import DNNClassifier, DNNRegressor, LinearClassifier, LinearRegressor, BoostedTreesClassifier, BoostedTreesRegressor, DNNLinearCombinedClassifier, DNNLinearCombinedRegressor
try:
    import sqlflow_models
except:
    pass
feature_column_names = [
"sepal_length",
"sepal_width",
"petal_length",
"petal_width",
]
feature_metas = dict()
feature_metas["sepal_length"] = {
    "feature_name": "sepal_length",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
feature_metas["sepal_width"] = {
    "feature_name": "sepal_width",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
feature_metas["petal_length"] = {
    "feature_name": "petal_length",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
feature_metas["petal_width"] = {
    "feature_name": "petal_width",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
label_meta = {
    "feature_name": "class",
    "dtype": "int64",
    "delimiter": "",
    "shape": [],
    "is_sparse": "false" == "true"
}
model_params=dict()
model_params["center_bias"]=True
model_params["n_batches_per_layer"]=8
model_params["n_classes"]=2
model_params["n_trees"]=50
feature_columns = {"feature_columns": [tf.feature_column.numeric_column("sepal_length", shape=[1]),
tf.feature_column.numeric_column("sepal_width", shape=[1]),
tf.feature_column.numeric_column("petal_length", shape=[1]),
tf.feature_column.numeric_column("petal_width", shape=[1])]}
import json
summaryAttrs = json.loads('''{}''')
explain.explain(datasource="mysql://root:root@tcp(127.0.0.1:3306)/?maxAllowedPacket=0",
                estimator_cls=BoostedTreesClassifier,
                select="""SELECT * FROM iris.test WHERE class!=2
	""",
                feature_columns=feature_columns,
                feature_column_names=feature_column_names,
                feature_metas=feature_metas,
                label_meta=label_meta,
                model_params=model_params,
                save="model_save",
                result_table="iris.explain_result",
                hdfs_namenode_addr="",
                hive_location="",
                hdfs_user="",
                hdfs_pass="",
                **summaryAttrs)
==========Output==========
Traceback (most recent call last):
  File "<stdin>", line 97, in <module>
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/explain.py", line 76, in explain
    gain = estimator.experimental_feature_importances(normalize=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1628, in experimental_feature_importances
    normalize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1461, in _compute_feature_importances
    assert normalizer > 0, 'Trees are all empty or contain only a root node.'
AssertionError: Trees are all empty or contain only a root node.
2020/01/10 07:42:53 stream read err: rpc error: code = Unknown desc = failed: exit status 1
==========Program==========
import tensorflow as tf
from sqlflow_submitter.tensorflow import explain
from tensorflow.estimator import DNNClassifier, DNNRegressor, LinearClassifier, LinearRegressor, BoostedTreesClassifier, BoostedTreesRegressor, DNNLinearCombinedClassifier, DNNLinearCombinedRegressor
try:
    import sqlflow_models
except:
    pass
feature_column_names = [
"sepal_length",
"sepal_width",
"petal_length",
"petal_width",
]
feature_metas = dict()
feature_metas["sepal_length"] = {
    "feature_name": "sepal_length",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
feature_metas["sepal_width"] = {
    "feature_name": "sepal_width",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
feature_metas["petal_length"] = {
    "feature_name": "petal_length",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
feature_metas["petal_width"] = {
    "feature_name": "petal_width",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}
label_meta = {
    "feature_name": "class",
    "dtype": "int64",
    "delimiter": "",
    "shape": [],
    "is_sparse": "false" == "true"
}
model_params=dict()
model_params["center_bias"]=True
model_params["n_batches_per_layer"]=8
model_params["n_classes"]=2
model_params["n_trees"]=50
feature_columns = {"feature_columns": [tf.feature_column.numeric_column("sepal_length", shape=[1]),
tf.feature_column.numeric_column("sepal_width", shape=[1]),
tf.feature_column.numeric_column("petal_length", shape=[1]),
tf.feature_column.numeric_column("petal_width", shape=[1])]}
import json
summaryAttrs = json.loads('''{}''')
explain.explain(datasource="mysql://root:root@tcp(127.0.0.1:3306)/?maxAllowedPacket=0",
                estimator_cls=BoostedTreesClassifier,
                select="""SELECT * FROM iris.test WHERE class!=2
	""",
                feature_columns=feature_columns,
                feature_column_names=feature_column_names,
                feature_metas=feature_metas,
                label_meta=label_meta,
                model_params=model_params,
                save="model_save",
                result_table="iris.explain_result",
                hdfs_namenode_addr="",
                hive_location="",
                hdfs_user="",
                hdfs_pass="",
                **summaryAttrs)
==========Output==========
Traceback (most recent call last):
  File "<stdin>", line 97, in <module>
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/explain.py", line 76, in explain
    gain = estimator.experimental_feature_importances(normalize=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1628, in experimental_feature_importances
    normalize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1461, in _compute_feature_importances
    assert normalizer > 0, 'Trees are all empty or contain only a root node.'
AssertionError: Trees are all empty or contain only a root node.
FAIL	sqlflow.org/sqlflow/cmd/sqlflowserver	34.989s
```

### PR DESCRIPTION
**Pull request by shendiaomo**
The original hyperparameter setting causes randomly training error.
Fix #1682

### CODE REVIEW

**Comment by tonyyang-svail** [comment]
Hi @shendiaomo, could you please mention how would batch_size affect the test stability?

```
Traceback (most recent call last):
  File "<stdin>", line 97, in <module>
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/explain.py", line 76, in explain
    gain = estimator.experimental_feature_importances(normalize=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1628, in experimental_feature_importances
    normalize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1461, in _compute_feature_importances
    assert normalizer > 0, 'Trees are all empty or contain only a root node.'
AssertionError: Trees are all empty or contain only a root node.
```

**Comment by shendiaomo** [comment]
> Hi @shendiaomo, could you please mention how would batch_size affect the test stability?
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 97, in <module>
>   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/explain.py", line 76, in explain
>     gain = estimator.experimental_feature_importances(normalize=True)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1628, in experimental_feature_importances
>     normalize)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1461, in _compute_feature_importances
>     assert normalizer > 0, 'Trees are all empty or contain only a root node.'
> AssertionError: Trees are all empty or contain only a root node.
> ```

IMO it's like the DNNs, larger batch size implies stabler gradients. For instance, a small batch size with a large learning rate always results in `NaN`s.

In `BoostedTreesEstimator`s, instead of  `batch_size` itself, it is `batch_size` and `n_batches_per_layer` that work together to do the same thing.

File: cmd/sqlflowserver/main_test.go [hunk 1]
```diff
@@ -677,11 +677,10 @@ func CaseTrainBoostedTreesEstimatorAndExplain(t *testing.T) {
 	SELECT * FROM iris.train WHERE class!=2
 	TO TRAIN BoostedTreesClassifier
 	WITH
-		model.n_batches_per_layer=8,
+		model.n_batches_per_layer=10,
 		model.n_trees=50,
-		model.n_classes=2,
```
Comment (typhoonzero) [inline cmd/sqlflowserver/main_test.go:682]: why remove `model.n_classes=2`?

Comment (shendiaomo) [reply cmd/sqlflowserver/main_test.go:682]: That is superfluous because the `BoostedTreesClassifier` is only capable of binary classification.
Of course, removing this has nothing to do with performance stability:-)

Comment (Yancey0623) [reply cmd/sqlflowserver/main_test.go:682]: Maybe we need to `assert model.n_cleasses == 2` instead of moving this argument.

**Review by Yancey0623 — APPROVED** [review]
LGTM with a comment: https://github.com/sql-machine-learning/sqlflow/pull/1677#discussion_r365192038

File: cmd/sqlflowserver/main_test.go (hunk 1 above)
Comment (shendiaomo) [reply cmd/sqlflowserver/main_test.go:682]: I think it's ok without an assertion, all `classifier`s in `tf.estimator` defaults to binary classification.
