### PR TITLE
Retry uploading sqlflow cli

### LINKED ISSUE #2305: QiNiu qshell doesn't work stablly in CI/CD
The releasing of the sqlflow client to QiNiu's object storage often fail with various errors.  A typical one is:

```
Uploading C:/Users/travis/gopath/src/sqlflow.org/sqlflow/build/sqlflow.exe => sqlflow-release : latest/windows/sqlflow ...
[I] 2020/05/19 06:08:21 resumable.Put retrying ... 3 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.30.0.11:50031->113.105.138.9:80: write tcp 10.30.0.11:50031->113.105.138.9:80: wsasend: An existing connection was forcibly closed by the remote host.
[I] 2020/05/19 06:13:21 resumable.Put retrying ... 3 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.30.0.11:50050->113.105.138.9:80: write tcp 10.30.0.11:50050->113.105.138.9:80: use of closed network connection
[W] 2020/05/19 06:20:48 resumable.Put 3 failed: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.30.0.11:50059->14.152.37.29:80: write tcp 10.30.0.11:50059->14.152.37.29:80: use of closed network connection
```

Let us consider a switch back to AWS S3.

### PR DESCRIPTION
**Pull request by typhoonzero**
Try fix https://github.com/sql-machine-learning/sqlflow/issues/2305

### CODE REVIEW

File: scripts/travis/deploy_client.sh [hunk 1]
```diff
@@ -92,7 +92,18 @@ export PATH=$PWD:$PATH
...
+        sqlflow-release \
+        "$RELEASE_TAG/$TRAVIS_OS_NAME/sqlflow" \
+        "$PWD"/build/sqlflow*)  # Need * because for Windows it is sqlflow.exe
+    echo "retrying in 3 seconds, left retry count $maxretry..."
+    sleep 3
+    maxretry=$(( maxretry - 1 ))
+    if [ $maxretry -eq 0 ]; then
+        break
+    fi
+done
```
Comment (wangkuiyi) [inline scripts/travis/deploy_client.sh:106]:
```bash
retry=0
while [[ $retry < 5 ]]; do
  if $F rput --overwrite \
        sqlflow-release \
        "$RELEASE_TAG/$TRAVIS_OS_NAME/sqlflow" \
        "$PWD"/build/sqlflow*; then
    break;
  fi
  retry=$(( retry + 1 ))
  sleep 3
done
```

Comment (wangkuiyi) [inline scripts/travis/deploy_client.sh:109]:
```bash
retry=0
while [[ $retry < 5 ]]; then
  if $F rput --overwrite \
        sqlflow-release \
        "$RELEASE_TAG/$TRAVIS_OS_NAME/sqlflow" \
        "$PWD"/build/sqlflow*; then
    break;
  fi;
  retry=$(( retry + 1 ))
  sleep 2
done
```

**Review by wangkuiyi — APPROVED** [review]

**Comment by wangkuiyi** [comment]
It seems that the CI on the develop branch might still fail after three retrials.

https://travis-ci.com/github/sql-machine-learning/sqlflow/jobs/339594913#L307-L317

```
Publish /tmp/sqlflow to Qiniu Object Storage ...
Uploading /Users/travis/gopath/src/sqlflow.org/sqlflow/build/sqlflow => sqlflow-release : latest/osx/sqlflow ...
[I] 2020/05/25 09:32:29 resumable.Put retrying ... 1 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.182.186.137:49834->14.152.37.7:80: write tcp 10.182.186.137:49834->14.152.37.7:80: use of closed network connection
[I] 2020/05/25 09:32:31 resumable.Put retrying ... 0 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.182.186.137:49836->14.152.37.7:80: write tcp 10.182.186.137:49836->14.152.37.7:80: use of closed network connection
[I] 2020/05/25 09:32:35 resumable.Put retrying ... 2 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.182.186.137:49833->14.152.37.7:80: write tcp 10.182.186.137:49833->14.152.37.7:80: use of closed network connection
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
