### PR TITLE
Disable bash substitution to make  backtick works in MaxCompute

### LINKED ISSUE #1966: Bad substitution error on SQL statement contains ${}
**Description**
If a SQL statement contains `${}`, for example
```
-- ${internal.config}
select 1;
```
In the workflow mode, the job will fail with the following error
```
bash: -- ${internal.config}
select 1;: bad substitution
```

**Reproduction Steps**
Execute the above example.

**Root Cause**
The workflow YAML produced by this SQL is 
```
container:
  command:
    - bash
    - '-c'
    - "repl -e \"-- ${internal.config}\nselect 1;\" "
```
And the workflow consider this as
```
bash -c repl -e "-- ${internal.config} select 1;"
```
So the bash command in the container tries to substitute `${internal.config}`. However, according to the bash man page
```
   name   A  word  consisting  only  of alphanumeric characters and under‐
          scores, and beginning with an alphabetic character or an  under‐
          score.  Also referred to as an identifier.
```
So the name `internal.config` with dot is illegal, then `bash` raises `bad substitution error`. [ref](https://unix.stackexchange.com/a/93533).

### LINKED ISSUE #1967: Question on workflow YAML
A typical workflow YAML contains the following command
```
container:
  command:
    - bash
    - '-c'
    - "repl -e \"select 1;\""
```
My concern is that the third argument 's double quotes will be dismissed after the translation. So the actual command becomes
```
bash -c repl -e "select 1;"
```
instead of
```
bash -c "repl -e \"select 1;\""
```

cc @Yancey1989 @weiguoz

### PR DESCRIPTION
**Pull request by shendiaomo**
Fix #1966 
Fix #1967

### CODE REVIEW

**Review by Yancey0623 — APPROVED** [review]
LGTM

File: pkg/workflow/couler/template.go [hunk 1]
```diff
@@ -56,7 +57,7 @@ if "{{.SecretName}}" != "":
 
 couler.clean_workflow_after_seconds_finished({{.WorkflowTTL}})
 def escape_sql(original_sql):
-	return original_sql.replace('"', '\\"')
+    return re.sub(r'(["$` + "`" + `\\])', r'\\\1', original_sql)
```
Comment (Yancey0623) [inline pkg/workflow/couler/template.go:60]: Add a sqlflow Couler step can avoid backtick in backtick. https://github.com/sql-machine-learning/sqlflow/pull/2060
