### PR TITLE
fix trim sql

### LINKED ISSUE #796: commit 2041069 cause select data problem
**Description**
2041069 support multiple sql statements in one rpc call (#740) # wrong
9edd805 [Design] Support multiple SQL statements (#779) # work
57b084d Grammatical improvement on design doc (#778) # work

**Reproduction Steps**
```
%%sqlflow
SELECT *
FROM datamap_test.ds_dnn_predict
LIMIT 10 ; 
```
**Expected Behavior**
What you expected to happen.

**Screenshots**
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/sqlflow/client.py in __repr__(self)
     58         table = PrettyTable(self._column_names)
     59         for row in self.rows():
---> 60             table.add_row(row)
     61         return table.__str__()
     62 

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/prettytable.py in add_row(self, row)
    816 
    817         if self._field_names and len(row) != len(self._field_names):
--> 818             raise Exception("Row has incorrect number of values, (actual) %d!=%d (expected)" %(len(row),len(self._field_names)))
    819         if not self._field_names:
    820             self.field_names = [("Field %d" % (n+1)) for n in range(0,len(row))]

Exception: Row has incorrect number of values, (actual) 0!=54 (expected)
```

### PR DESCRIPTION
**Pull request by Yancey0623**
fixed #796

### CODE REVIEW

File: server/sqlflowserver.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func (s *Server) Run(req *pb.Request, stream pb.SQLFlow_RunServer) error {
 	sqlStatements := strings.Split(req.Sql, ";")
 	trimedStatements := []string{}
 	for _, singleSQL := range sqlStatements {
-		sqlToRun := strings.Trim(singleSQL, "\n")
+		sqlToRun := strings.TrimSpace(singleSQL)
```
Comment (typhoonzero) [inline server/sqlflowserver.go:65]: maybe `\n` also need to be trimmed?

Comment (Yancey0623) [reply server/sqlflowserver.go:65]: `strings.TrimSpace` can trim `\n` and space: https://golang.org/pkg/strings/#TrimSpace

**Review by typhoonzero — APPROVED** [review]
