### PR TITLE
Verify Prediction tablename 

### LINKED ISSUE #1129: Wrongly recognize database and table with same name in predict clause
**Description**
When user has named one table by the same name of database, SQLFlow cannot distinguish them in predict clause.

**Reproduction Steps**
```
...
PREDICT database_test.iris_predict.class
...
```
will fail when there is a table named `database_test` in database `database_test`

It can be temporarily solved by remove the table name in predict clause like `PREDICT iris_predict.class`.

### PR DESCRIPTION
**Pull request by Yancey0623**
fixed #1129

### CODE REVIEW

File: pkg/sql/ir_generator.go [hunk 1]
```diff
@@ -569,16 +569,15 @@ func parseShape(e *expr) ([]int, error) {
...
 	resultTableParts := strings.Split(intoStatement, ".")
 	if len(resultTableParts) == 3 {
 		return strings.Join(resultTableParts[0:2], "."), resultTableParts[2], nil
-	} else if len(resultTableParts) == 2 || len(resultTableParts) == 1 {
-		return intoStatement, "", nil
+	} else if len(resultTableParts) == 2 {
+		return resultTableParts[0], resultTableParts[1], nil
 	} else {
-		return "", "", fmt.Errorf("error result table format, should be db.table.class_col or db.table or table")
+		return "", "", fmt.Errorf("invalied result table format, should be [db.table.class_col] or [table.class_col]")
```
Comment (terrytangyuan) [inline pkg/sql/ir_generator.go:581]: Invalid

**Review by tonyyang-svail — APPROVED** [review]
LGTM.
