### PR TITLE
Fix random failure on TestValidateAttribute

### LINKED ISSUE #691: Random fail on TestValidateAttribute
**Description**
```
$ go test -run TestValidateAttribute
--- FAIL: TestValidateAttribute (0.00s)
    attribute_validator_test.go:30:
        	Error Trace:	attribute_validator_test.go:30
        	Error:      	Expected nil, but got: &errors.errorString{s:"Attribute value is not string type, [100 200 300]"}
        	Test:       	TestValidateAttribute
FAIL
exit status 1
FAIL	github.com/sql-machine-learning/sqlflow/sql	0.150s
```

**Reproduction Steps**
Run `go test -run TestValidateAttribute` many times.

**Additional Notes**
The cause of the random failure is explained at https://github.com/sql-machine-learning/sqlflow/pull/676#pullrequestreview-277495067

### PR DESCRIPTION
**Pull request by tonyyang-svail**
Fix #691

### CODE REVIEW

**Review by typhoonzero — DISMISSED** [review]
Thanks

File: sql/attribute_validator.go [hunk 1]
```diff
@@ -33,33 +33,24 @@ func ValidateAttributes(attrs map[string]*attribute) error {
...
+			if govalidator.IsInt(value) || govalidator.IsFloat(value) || govalidator.IsJSON(value) || govalidator.IsASCII(value) {
+				continue
 			}
-		} else if _, ok := v.Value.([]interface{}); ok {
-			// a list attribute
-			return nil
-		} else {
-			return fmt.Errorf("Attribute value is not string type, %v", v.Value)
+			return fmt.Errorf("not supported attribute value: %s", value)
+		case []int:
```
Comment (typhoonzero) [inline sql/attribute_validator.go]: should convert to `[]interface{}` first

**Comment by typhoonzero** [comment]
May still need to change https://github.com/sql-machine-learning/sqlflow/pull/688/files#diff-dd1a4b4831351baba574b3de16c35379R43 to `predict` to pass the CI

**Review by typhoonzero — APPROVED** [review]
LGTM
