### PR TITLE
diagnosis missing model params

### LINKED ISSUE #2184: Optimize error message on missing required model arguments
``` sql
SELECT * from iris.train TO TRAIN DNNClassifier WITH model.n_classes=3 LABEL class INTO iris.xgb;
```

What we have
``` text
Traceback (most recent call last):

  File "<stdin>", line 136, in <module>

  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 126, in train

    save_checkpoints_steps, validation_metrics)

  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train_estimator.py", line 54, in estimator_train_and_save

    classifier = estimator(**model_params)

TypeError: __init__() missing 1 required positional argument: 'hidden_units'

ERROR: rpc error: code = Unknown desc = runSQLProgram error: failed: exit status 1
==========Program==========

import copy
import tensorflow as tf
from sqlflow_submitter.tensorflow.train import train
from sqlflow_submitter.tensorflow.get_tf_version import tf_is_version2
from tensorflow.estimator import (DNNClassifier,
                                  DNNRegressor,
                                  LinearClassifier,
                                  LinearRegressor,
                                  BoostedTreesClassifier,
                                  BoostedTreesRegressor,
                                  DNNLinearCombinedClassifier,
                                  DNNLinearCombinedRegressor)
if tf_is_version2():
    from tensorflow.keras.optimizers import Adadelta, Adagrad, Adam, Adamax, Ftrl, Nadam, RMSprop, SGD
    from tensorflow.keras.losses import BinaryCrossentropy, CategoricalCrossentropy, CategoricalHinge, CosineSimilarity, Hinge, Huber, KLDivergence, LogCosh, MeanAbsoluteError, MeanAbsolutePercentageError, MeanSquaredError, MeanSquaredLogarithmicError, Poisson, SparseCategoricalCrossentropy, SquaredHinge
else:
    from tensorflow.train import AdadeltaOptimizer, AdagradOptimizer, AdamOptimizer, FtrlOptimizer, RMSPropOptimizer, GradientDescentOptimizer, MomentumOptimizer
    from tensorflow.keras.losses import BinaryCrossentropy, CategoricalCrossentropy, CategoricalHinge, CosineSimilarity, Hinge, Huber, KLDivergence, LogCosh, MeanAbsoluteError, MeanAbsolutePercentageError, MeanSquaredError, MeanSquaredLogarithmicError, Poisson, SparseCategoricalCrossentropy, SquaredHinge
try:
    import sqlflow_models
except Exception as e:
    print("failed to import sqlflow_models: %s", e)

feature_column_names = [
"sepal_length",

"sepal_width",

"petal_length",

"petal_width",
]

# feature_column_names_map is used to determine the order of feature columns of each target:
# e.g. when using DNNLinearCombinedClassifer.
# feature_column_names_map will be saved to a single file when using PAI.
feature_column_names_map = dict()

feature_column_names_map["feature_columns"] = ["sepal_length","sepal_width","petal_length","petal_width",]


feature_metas = dict()


feature_metas["sepal_length"] = {
    "feature_name": "sepal_length",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}

feature_metas["sepal_width"] = {
    "feature_name": "sepal_width",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}

feature_metas["petal_length"] = {
    "feature_name": "petal_length",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}

feature_metas["petal_width"] = {
    "feature_name": "petal_width",
    "dtype": "float32",
    "delimiter": "",
    "shape": [1],
    "is_sparse": "false" == "true"
}



label_meta = {
    "feature_name": "class",
    "dtype": "int64",
    "delimiter": "",
    "shape": [],
    "is_sparse": "false" == "true"
}

model_params=dict()

model_params["n_classes"]=3


# Construct optimizer objects to pass to model initializer.
# The original model_params is serializable (do not have tf.xxx objects).
model_params_constructed = copy.deepcopy(model_params)
for optimizer_arg in ["optimizer", "dnn_optimizer", "linear_optimizer"]:
    if optimizer_arg in model_params_constructed:
        model_params_constructed[optimizer_arg] = eval(model_params_constructed[optimizer_arg])

if "loss" in model_params_constructed:
    model_params_constructed["loss"] = eval(model_params_constructed["loss"])

# feature_columns_code will be used to save the training informations together
# with the saved model.
feature_columns_code = """{"feature_columns": [tf.feature_column.numeric_column("sepal_length", shape=[1]),
tf.feature_column.numeric_column("sepal_width", shape=[1]),
tf.feature_column.numeric_column("petal_length", shape=[1]),
tf.feature_column.numeric_column("petal_width", shape=[1])]}"""
feature_columns = eval(feature_columns_code)

train_max_steps = 0
train_max_steps = None if train_max_steps == 0 else train_max_steps

train(datasource="mysql://root:root@tcp(127.0.0.1:3306)/?maxAllowedPacket=0",
      estimator=DNNClassifier,
      select="""SELECT * from iris.train """,
      validation_select="""""",
      feature_columns=feature_columns,
      feature_column_names=feature_column_names,
      feature_metas=feature_metas,
      label_meta=label_meta,
      model_params=model_params_constructed,
      validation_metrics="Accuracy".split(","),
      save="model_save",
      batch_size=1,
      epoch=1,
      validation_steps=1,
      verbose=0,
      max_steps=train_max_steps,
      validation_start_delay_secs=0,
      validation_throttle_secs=0,
      save_checkpoints_steps=100,
      log_every_n_iter=10,
      is_pai="false" == "true",
      pai_table="",
      pai_val_table="")

==========Output==========
Start training using estimator model...
Traceback (most recent call last):
  File "<stdin>", line 136, in <module>
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 126, in train
    save_checkpoints_steps, validation_metrics)
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train_estimator.py", line 54, in estimator_train_and_save
    classifier = estimator(**model_params)
TypeError: __init__() missing 1 required positional argument: 'hidden_units'
```

What we want

```text
error: required argument missed: hidden_units of DNNClassifier must be provided
```

### PR DESCRIPTION
**Pull request by Yancey0623**
part fixed #2184

### CODE REVIEW

File: cmd/sqlflowserver/main_test.go [hunk 1]
```diff
@@ -350,6 +349,21 @@ func TestEnd2EndMySQL(t *testing.T) {
...
+func CaseDiagnosisMissingModelParams(t *testing.T) {
+	a := assert.New(t)
+	trainSQL := `SELECT * FROM iris.train TO TRAIN DNNClassifier WITH
+  model.n_classes = 3,
+  train.epoch = 10
+COLUMN sepal_length, sepal_width, petal_length, petal_width
+LABEL class
+INTO sqlflow_models.my_dnn_model;`
+	_, _, _, err := connectAndRunSQL(trainSQL)
+	a.Contains(err.Error(), "model attribute missing 1 required positional argument: 'hidden_units'")
```
Comment (shendiaomo) [inline cmd/sqlflowserver/main_test.go]: This not user-friendly enough, `positional arguments` is a Python terminology, and `model attribute` is inconsistent with the following `argument`, an ideal diagnostics message should be at least something like:
```
DNNClassifier missing 1 required attribute: model.hidden_units (type: integer list)"
```

**Comment by shendiaomo** [comment]
Can we rename `diagnosis` to `diagnostics` or simply `diag`? 
1. `diagnostics` is the standard term for this concept:
    image
    https://github.com/gcc-mirror/gcc/blob/master/gcc/diagnostic.c
1. `diag` is the standard abbreviation for `diagnostics`:
    https://github.com/gcc-mirror/gcc/blob/bc35ef6543424134df1619909df728a52d6f1f7f/gcc/diagnostic-core.h#L54-L61

File: cmd/sqlflowserver/main_test.go (hunk 1 above)
Comment (Yancey0623) [reply cmd/sqlflowserver/main_test.go]: Diagnosis argument type error would be more complex, will implement it in the next PR.

File: python/sqlflow_submitter/tensorflow/diag.py [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+import re
+
+
+class SQLFlowDiagnostic(Exception):
```
Comment (typhoonzero) [inline python/sqlflow_submitter/tensorflow/diag.py:16]: Exception names should be like `XXXError` and `XXXException`?

**Review by typhoonzero — APPROVED** [review]
LGTM with a tiny comment.

File: python/sqlflow_submitter/tensorflow/diag.py (hunk 2 above)
Comment (Yancey0623) [reply python/sqlflow_submitter/tensorflow/diag.py:16]: From https://www.python.org/dev/peps/pep-0008/#exception-names

> Because exceptions should be classes, the class naming convention applies here. However, you should use the suffix "Error" on your exception names (if the exception actually is an error).

Maybe `Diagnostic` is more accurate.

Comment (typhoonzero) [reply python/sqlflow_submitter/tensorflow/diag.py:16]: It's indeed some error I think? When some error occurs, we should analyze the error and return useful messages, and this process is "Diagnostic".

Comment (Yancey0623) [reply python/sqlflow_submitter/tensorflow/diag.py:16]: I see what you mean, `raise an SQLFlowDiagnositic Error ` is more accurate, will update this class name in the next PR.
