### PR TITLE
Fast fail REPL if DB connection fails && Add test cases for this

### LINKED ISSUE #1338: REPL shows an unpleasant  error message if its connection is refused
image

On the opposite, the MySQL client shows a more friendly message in the same situation:
image

### PR DESCRIPTION
**Pull request by shendiaomo**
1. Fix #1338 and add a couple of test cases to ensure it's fixed.
2. Propose a mechanism to test the `main` function and its exit status.

### CODE REVIEW

File: cmd/repl/repl_test.go [hunk 1]
```diff
@@ -36,6 +39,44 @@ import (
 
 var space = regexp.MustCompile(`\s+`)
 
+func testMainFastFail(t *testing.T, interactive bool) {
+	a := assert.New(t)
+	// Run the crashing code when FLAG is set
+	if os.Getenv("FLAG") == "false" {
```
Comment (wangkuiyi) [inline cmd/repl/repl_test.go]: For less probability of name conflicting, I assume we'd change `FLAG` to a longer and more precise name like `SQLFLOW_TEST_FAST_FAIL_INTERACTIVE_OR_NOT`.

**Review by wangkuiyi — COMMENTED** [review]
Issue #1338 is about SQLFlow doesn't present a friendly error message when DB connection fails. I don't understand why we could fix this issue by adding a unit test?

File: cmd/repl/repl_test.go (hunk 1 above)
Comment (shendiaomo) [reply cmd/repl/repl_test.go]: > Issue #1338 is about SQLFlow doesn't present a friendly error message when DB connection fails. I don't understand why we could fix this issue by adding a unit test?

The bug in #1338 occurs since the original `repl.go` doesn't check the connectability of DB before entering the interactive mode. The fix is actually the new  function `assertConnectable` in `repl.go`. and the call to it in the function `main`

Comment (shendiaomo) [reply cmd/repl/repl_test.go]: > For less probability of name conflicting, I assume we'd change `FLAG` to a longer and more precise name like `SQLFLOW_TEST_FAST_FAIL_INTERACTIVE_OR_NOT`.

Done.

**Review by tonyyang-svail — APPROVED** [review]
LGTM.
