### PR TITLE
fix run normal query statements have comments

### LINKED ISSUE #2231: Comment in SQL program
The selected rows are empty if the query contains a comment.

It works well with MySQL cmd:
```bash
mysql -uroot -proot -e "-- I'm a comment
> select 1;
> "
mysql: [Warning] Using a password on the command line interface can be insecure.
+---+
| 1 |
+---+
| 1 |
+---+
```

But the query returned an empty result with SQLFlow step cmd: 
``` bash
step -e "-- I'm a comment
> SELECT 1;
> "
2020/05/13 07:25:56 SQLFlow Step Execute:
-- I'm a comment
SELECT 1;

0 row affected
(0.00 sec)
```

SQLFlow CLI command-line works well:
``` bash
sqlflow -e "-- I'm comment
SELECT 1;
"
found comment,  1 0 0
sqlflow> SELECT 1;
+---+
| 1 |
+---+
| 1 |
+---+
```

### PR DESCRIPTION
**Pull request by typhoonzero**
Fix https://github.com/sql-machine-learning/sqlflow/issues/2231

### CODE REVIEW

**Review by Yancey0623 — APPROVED** [review]
LGTM

File: pkg/sql/executor_normal_stmt.go [hunk 1]
```diff
@@ -35,6 +35,17 @@ func runNormalStmt(wr *pipe.Writer, slct string, db *database.DB) error {
 func isQuery(slct string) bool {
 	s := strings.ToUpper(strings.TrimSpace(slct))
 	has := strings.Contains
+	// remove comment lines
+	if strings.HasPrefix(s, "-- ") {
```
Comment (Yancey0623) [inline pkg/sql/executor_normal_stmt.go:39]: Also need to support multi-line comment: `/** .... **/`, can merge this PR and update in the future.

Comment (typhoonzero) [reply pkg/sql/executor_normal_stmt.go:39]: Sure.
