### PR TITLE
Simple support for text classification

### LINKED ISSUE #370: SyntaxError: invalid syntax - Custom dataset
Dataset: [chinese_news_dataset](https://github.com/fate233/toutiao-text-classfication-dataset)

**SQLFlow SQL:**
```sql
SELECT *
FROM sqlflow.train
TRAIN DNNClassifier
WITH
  n_classes = 15,
  hidden_units = [10, 20]
COLUMN news_title
LABEL class_name
INTO sqlflow_models.my_dnn_model;
```
**Return logs:**
```python
INFO[0036] tensorflowCmd: run locally                    package=sql
  File "<stdin>", line 34

    feature_columns = [tf.feature_column.(key="news_title"),

                                         ^

SyntaxError: invalid syntax

ERRO[0036] runExtendedSQL error:training failed exit status 1  package=sql
ERROR: training failed exit status 1
```

**Table info:**
```sql
CREATE TABLE `toutiao` (
  `id` bigint(20) NOT NULL,
  `class_id` int(3) NOT NULL,
  `class_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `news_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `news_keywords` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
COMMIT;
```

**Simple data:**
```
|        id          | class_id | class_name  |                     news_title                     |                                       news_keywords                                       |
+---------------------+----------+--------------+----------------------------------------------------+-------------------------------------------------------------------------------------------+
| 6552368441838272771 |      101 | news_culture | 发酵床的垫料种类有哪些？哪种更好？                 |                                                                                           |
| 6552407965343678723 |      101 | news_culture | 上联：黄山黄河黄皮肤黄土高原。怎么对下联？         |                                                                                           |
| 6552332417753940238 |      101 | news_culture | 林徽因什么理由拒绝了徐志摩而选择梁思成为终身伴侣？ |                                                                                           |
| 6552475601595269390 |      101 | news_culture | 黄杨木是什么树？                                   |                                                                                           |
| 6552387648126714125 |      101 | news_culture | 上联：草根登上星光道，怎么对下联？                 |                                                                                           |
| 6552271725814350087 |      101 | news_culture | 什么是超写实绘画？                                 |                                                                                           |
| 6552452982015787268 |      101 | news_culture | 松涛听雨莺婉转，下联？                             |                                                                                           |
| 6552400379030536455 |      101 | news_culture | 上联：老子骑牛读书，下联怎么对？                   |                                                                                           |
| 6552339283632455939 |      101 | news_culture | 上联：山水醉人何须酒。如何对下联？                 |                                                                                           |

```

### PR DESCRIPTION
**Pull request by typhoonzero**
Fix https://github.com/sql-machine-learning/sqlflow/issues/370

TODO: need to discuss about how to configure `num_buckets` and embedding `dimension`

**NOTE**, need to run preprocess script listed in #370. 

NOTE, need pre process the class_id to `class_id -100` for tensorflow deal with label starts from 0. Below sql will achieve accuracy 0.89608 using `BATCHSIZE=100` and `STEP=5000`

```
SELECT *
FROM toutiao.train_processed
TRAIN DNNClassifier
WITH
  n_classes = 117,
  hidden_units = [128, 512]
COLUMN news_title
LABEL class_id
INTO sqlflow_models.my_dnn_model;
```

### CODE REVIEW

File: scripts/test.sh [hunk 1]
```diff
@@ -5,6 +5,7 @@ service mysql start
 
 cat example/datasets/popularize_churn.sql | mysql -uroot -proot
 cat example/datasets/popularize_iris.sql | mysql -uroot -proot
+cat example/datasets/popularize_toutiao.sql | mysql -uroot -proot
```
Comment (tonyyang-svail) [inline scripts/test.sh:8]: Is there a way to combine `sql/testdata` and `example/datasets/*.sql`?

Comment (typhoonzero) [reply scripts/test.sh:8]: Should be. Since https://github.com/sql-machine-learning/sqlflow/issues/404 is describing the same thing, I'll try to fix this in another PR.

**Review by tonyyang-svail — APPROVED** [review]
LGTM!

File: scripts/test.sh (hunk 1 above)
Comment (tonyyang-svail) [reply scripts/test.sh:8]: Sounds good!

File: sql/codegen.go [hunk 2]
```diff
@@ -154,9 +162,12 @@ import logging
 tf.get_logger().setLevel(logging.ERROR)
 ` +
 	// TODO(tonyyang-svail): remove hard coded BATCHSIZE, STEP
+	// TODO(typhoonzero): get NUM_BUCKETS, EMBEDDING_WIDTH from Extended SQL statements
```
Comment (hungry1526) [inline sql/codegen.go:165]: For every TODO, would it be better to create an issue and we can track it without going through the code?
