### PR TITLE
Polish argo/fetch.go 

### LINKED ISSUE #1412: TestGetPodLogs fails randomly
To reproduce, we can run TestGetPodLogs many times.

Sample script:
```
set -e
for i in {0..100}; do
	echo $i
	go test -run TestGetPodLogs
done
```

The test failed at the 17th run.
```
sqlflow/pkg/argo# bash long_test.sh
...
15
PASS
ok  	sqlflow.org/sqlflow/pkg/argo	10.109s
16
PASS
ok  	sqlflow.org/sqlflow/pkg/argo	8.144s
17
--- FAIL: TestGetPodLogs (9.48s)
    fetch_test.go:305:
        	Error Trace:	fetch_test.go:305
        	Error:      	Not equal:
        	            	expected: []string{"hello1", "hello2"}
        	            	actual  : []string{"hello1", "hello2", "hello3"}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,5 @@
        	            	-([]string) (len=2) {
        	            	+([]string) (len=3) {
        	            	  (string) (len=6) "hello1",
        	            	- (string) (len=6) "hello2"
        	            	+ (string) (len=6) "hello2",
        	            	+ (string) (len=6) "hello3"
        	            	 }
        	Test:       	TestGetPodLogs
FAIL
exit status 1
FAIL	sqlflow.org/sqlflow/pkg/argo	9.512s
```

Related code

https://github.com/sql-machine-learning/sqlflow/blob/a8ac42faf442900269995dd2d5bc2f649c2a6c3d/pkg/argo/fetch_test.go#L275-L302

### PR DESCRIPTION
**Pull request by Yancey0623**
following https://github.com/sql-machine-learning/sqlflow/pull/1400#pullrequestreview-331657078
fixed #1412

### CODE REVIEW

File: pkg/argo/fetch_test.go [hunk 1]
```diff
@@ -277,26 +272,28 @@ func TestGetPodLogs(t *testing.T) {
...
+	defer kubectlDeletePod(podID)
 
 	err = waitUntilPodRunning(podID)
 	a.NoError(err)
 	offset := ""
-	realLogs := []string{}
+	actual := []string{}
+	expected := []string{"hello1", "hello2", "hello3"}
 	for {
+		isPodCompleted := isPodCompleted(podID)
```
Comment (Yancey0623) [inline pkg/argo/fetch_test.go:285]: Get the latest pod status can fix the random failed.

**Review by typhoonzero — APPROVED** [review]

File: pkg/argo/fetch_test.go (hunk 1 above)
Comment (tonyyang-svail) [reply pkg/argo/fetch_test.go:285]: Good catch.
