### PR TITLE
Providing more explicit error message about the lack of OSS auth

### LINKED ISSUE #2679: Providing more explicit error message about the lack of OSS access permissions
If we did not add authorization for the `PAI` to access `OSS`, the `PAI` throw out a message:
```
...
train: running
train: running
Instance 2020071***m3 Failed.
FAILED: Failed 26***306:kNotFound:The role_arn you provide not exists in OSS auth service. Please check carefully.
task exec failed
run task finished...
2020-07-15 14:53:28 INFO =================================================================
2020-07-15 14:53:28 INFO Exit code of the Shell command 1
2020-07-15 14:53:28 INFO --- Invocation of Shell command completed ---
```

We may grep `The role_arn you provide not exists in OSS auth service` in the [log](https://github.com/sql-machine-learning/sqlflow/blob/c1a15910ff6ed3e6e4f94bc7c8a39eea96396c9e/go/executor/alisa.go#L76) to provide a better user experience.

### PR DESCRIPTION
**Pull request by weiguoz**
Fix #2679

### CODE REVIEW

File: go/executor/pai.go [hunk 1]
```diff
@@ -715,3 +719,16 @@ func (s *paiExecutor) GetTrainStmtFromModel() bool { return false }
 func pickPAILogViewerURL(output string) []string {
 	return reODPSLogURL.FindAllString(output, -1)
 }
+
+func guessError(taskType, output string) error {
```
Comment (Yancey0623) [inline go/executor/pai.go]: we already give the suggestion to users, so maybe the function name can be `disgnostic`.

**Review by Yancey0623 — APPROVED** [review]
LGTM
