### PR TITLE
fix experimental codegen model zoo test cases

### LINKED ISSUE #2978: ModelZoo does not support the saved model using the refactorized codes
Based on https://github.com/sql-machine-learning/sqlflow/pull/2970 .

In the refactorized codes, we save the trained model in the way of (see the [design doc](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/get_model_metadata_in_prediction_codegen.md)):

```
+-----+----------------------------------------------------------+
| id  |                         block                            |
+-----|----------------------------------------------------------+
|  0  |                                                          |
|  1  | (metadata_length, metadata, model structure and weights) |
| ... |                                                          |
+-----+----------------------------------------------------------+
```

But we saved the trained model in the following way when using the old codes:

```
+-----+-----------------------------+
| id  |           block             |
+-----|-----------------------------+
|  0  |                             |
|  1  | model structure and weights |
| ... |                             |
+-----+-----------------------------+
```

These two saving ways are quite different. The model zoo codes should meet the requirements of the refactorized model saving ways. 

The error is:
```
2020-09-30T01:36:02.7254282Z [0m[91m--- FAIL: TestModelZooOperation (8.87s)
2020-09-30T01:36:02.7255836Z [0m[32m    --- PASS: TestModelZooOperation/caseReleaseRepo (2.47s)
2020-09-30T01:36:02.7257524Z [0m[32m    --- PASS: TestModelZooOperation/caseTrainModel (6.28s)
2020-09-30T01:36:02.7259220Z [0m[91m    --- FAIL: TestModelZooOperation/caseReleaseModel (0.02s)
2020-09-30T01:36:02.7259969Z [0m[0m        model_zoo_client_test.go:104: 
2020-09-30T01:36:02.7260605Z [0m[0m            	Error Trace:	model_zoo_client_test.go:104
2020-09-30T01:36:02.7261207Z [0m[0m            	Error:      	Received unexpected error:
2020-09-30T01:36:02.7262048Z [0m[0m            	            	rpc error: code = Unknown desc = can't unzip model tarball /tmp/upload_model_zoo047999757/model_dump.tar.gz: 
2020-09-30T01:36:02.7262870Z [0m[0m            	            	gzip: stdin: not in gzip format
2020-09-30T01:36:02.7263420Z [0m[0m            	            	tar: Child returned status 1
2020-09-30T01:36:02.7264257Z [0m[0m            	            	tar: Error is not recoverable: exiting now
2020-09-30T01:36:02.7264800Z [0m[0m            	            	, exit status 2
2020-09-30T01:36:02.7265463Z [0m[0m            	Test:       	TestModelZooOperation/caseReleaseModel
2020-09-30T01:36:02.7266377Z [0m[91m    --- FAIL: TestModelZooOperation/caseReleaseModelLocal (0.01s)
2020-09-30T01:36:02.7267106Z [0m[0m        model_zoo_client_test.go:114: 
2020-09-30T01:36:02.7268210Z [0m[0m            	Error Trace:	model_zoo_client_test.go:114
2020-09-30T01:36:02.7271311Z [0m[0m            	Error:      	Received unexpected error:
2020-09-30T01:36:02.7272670Z [0m[0m            	            	rpc error: code = Unknown desc = can't unzip model tarball /tmp/upload_model_zoo367317768/model_dump.tar.gz: 
2020-09-30T01:36:02.7273990Z [0m[0m            	            	gzip: stdin: not in gzip format
2020-09-30T01:36:02.7274568Z [0m[0m            	            	tar: Child returned status 1
2020-09-30T01:36:02.7275185Z [0m[0m            	            	tar: Error is not recoverable: exiting now
2020-09-30T01:36:02.7275731Z [0m[0m            	            	, exit status 2
2020-09-30T01:36:02.7276437Z [0m[0m            	Test:       	TestModelZooOperation/caseReleaseModelLocal
2020-09-30T01:36:02.7277329Z [0m[91m    --- FAIL: TestModelZooOperation/caseListModels (0.01s)
2020-09-30T01:36:02.7277987Z [0m[0m        model_zoo_client_test.go:141: 
2020-09-30T01:36:02.7278533Z [0m[0m            	Error Trace:	model_zoo_client_test.go:141
2020-09-30T01:36:02.7279127Z [0m[0m            	Error:      	"" does not contain "iris.my_model"
2020-09-30T01:36:02.7279812Z [0m[0m            	Test:       	TestModelZooOperation/caseListModels
```

```
2020-09-30T01:47:28.3345170Z [0m[0m=== RUN   TestUsingModelZooModel
2020-09-30T01:47:28.3396091Z [0m[0mtime="2020-09-30T09:47:28+08:00" level=info msg="SQLFlow Model Zoo started at: 50056"
2020-09-30T01:47:47.1095987Z [0m[91m--- FAIL: TestUsingModelZooModel (18.77s)
2020-09-30T01:47:47.1097134Z [0m[0m    using_model_test.go:184: 
2020-09-30T01:47:47.1097954Z [0m[0m        	Error Trace:	using_model_test.go:184
2020-09-30T01:47:47.1098843Z [0m[0m        	Error:      	Received unexpected error:
2020-09-30T01:47:47.1103412Z [0m[0m        	            	rpc error: code = Unknown desc = can't unzip model tarball /tmp/upload_model_zoo323671219/model_dump.tar.gz: 
2020-09-30T01:47:47.1104511Z [0m[0m        	            	gzip: stdin: not in gzip format
2020-09-30T01:47:47.1106242Z [0m[0m        	            	tar: Child returned status 1
2020-09-30T01:47:47.1114646Z [0m[0m        	            	tar: Error is not recoverable: exiting now
2020-09-30T01:47:47.1115621Z [0m[0m        	            	, exit status 2
2020-09-30T01:47:47.1116230Z [0m[0m        	Test:       	TestUsingModelZooModel
2020-09-30T01:47:47.1116812Z [0m[0m    using_model_test.go:189: 
2020-09-30T01:47:47.1117332Z [0m[0m        	Error Trace:	using_model_test.go:189
2020-09-30T01:47:47.1117900Z [0m[0m        	Error:      	Received unexpected error:
2020-09-30T01:47:47.1118731Z [0m[0m        	            	rpc error: code = Unknown desc = runSQLProgram error: exit status 1: Traceback (most recent call last):
2020-09-30T01:47:47.1119643Z [0m[0m        	            	  File "/tmp/sqlflow-couler-tmp219763549", line 5, in <module>
2020-09-30T01:47:47.1120586Z [0m[0m        	            	    print(pyfunc.body(step_entry_0))
2020-09-30T01:47:47.1121853Z [0m[0m        	            	NameError: name 'step_entry_0' is not defined
2020-09-30T01:47:47.1122746Z [0m[0m        	            	
2020-09-30T01:47:47.1123401Z [0m[0m        	            	Code is:
2020-09-30T01:47:47.1124052Z [0m[0m        	            	
2020-09-30T01:47:47.1124713Z [0m[0m        	            	
2020-09-30T01:47:47.1125259Z [0m[0m        	            	
2020-09-30T01:47:47.1125754Z [0m[0m        	            	import couler.pyfunc as pyfunc
2020-09-30T01:47:47.1126493Z [0m[0m        	            	print(pyfunc.body(step_entry_0))
2020-09-30T01:47:47.1127137Z [0m[0m        	Test:       	TestUsingModelZooModel
2020-09-30T01:47:47.1127645Z [0m[91mFAIL
```

### PR DESCRIPTION
**Pull request by typhoonzero**
Fix #2978

### CODE REVIEW

File: go/codegen/experimental/codegen_step.go [hunk 1]
```diff
@@ -168,24 +169,21 @@ func getModelMetadataFromDB(dbConnStr, table string) (*metadata, error) {
...
-	readCnt, err = fs.Read(jsonBytes)
+	metaLength, err := strconv.ParseInt(string(lengthHexStr), 0, 64)
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("convert length head error: %v", err)
 	}
-	if uint64(readCnt) != length {
-		return nil, fmt.Errorf("invalid model metadata")
+	jsonBytes := make([]byte, metaLength)
+	_, err = fs.Read(jsonBytes)
```
Comment (sneaxiy) [inline go/codegen/experimental/codegen_step.go]: How about check the read count is equal to `metaLength`?

File: go/model/model.go [hunk 2]
```diff
@@ -306,6 +307,45 @@ func ExtractMetaFromTarball(tarballName, cwd string) (*Model, error) {
...
+	n, err := sqlf.Read(lengthHexStr)
+	if err != nil || n != 10 {
+		return "", nil, fmt.Errorf("read meta length from db error: %v", err)
+	}
+	metaLength, err := strconv.ParseInt(string(lengthHexStr), 0, 64)
+	if err != nil {
+		return "", nil, fmt.Errorf("convert length head error: %v", err)
+	}
+	metaStr := make([]byte, metaLength)
+	_, err = sqlf.Read(metaStr)
```
Comment (sneaxiy) [inline go/model/model.go]: How about check the read count is equal to `metaLength`?

**Review by sneaxiy — APPROVED** [review]
