### PR TITLE
Remove unnecessary log.Print

### LINKED ISSUE #894: Remove unnecessary fmt.Print
`fmt.Printf` in `sql` packages should change to `log.Info` or `log.Debug`.
```bash
(develop)$ git grep fmt.P
cmd/repl/repl.go:               fmt.Printf("ERROR: %v\n", s)
cmd/repl/repl.go:               fmt.Println(s)
cmd/repl/repl.go:               fmt.Print("sqlflow> ")
cmd/repl/repl.go:               fmt.Println("")
cmd/repl/repl.go:               fmt.Println("")
sql/codegen_alps_test.go:       fmt.Println(filler.FeatureColumnCode)
sql/expression_resolver.go:             fmt.Printf("ignore invalid %s=%s, default is %d", key, p.Value, defaultValue)
sql/expression_resolver.go:                     fmt.Printf("ignore invalid %s=%s, default is %v", key, p.Value, defaultValue)
sql/sql_test.go:                fmt.Println(e)
sqlfs/sqlfile_test.go:          fmt.Println(e)
```

### PR DESCRIPTION
**Pull request by wangkuiyi**
Fix https://github.com/sql-machine-learning/sqlflow/issues/894

### CODE REVIEW

File: sql/sql_test.go [hunk 1]
```diff
@@ -113,7 +113,6 @@ func TestMain(m *testing.M) {
 // log doesn't work.
 func assertNoErr(e error) {
 	if e != nil {
-		fmt.Println(e)
```
Comment (tonyyang-svail) [inline sql/sql_test.go]: I will revert this change due to the comment "log doesn't work" by @wangkuiyi 

https://github.com/sql-machine-learning/sqlflow/blob/572b23a37ccfd9f4041ede14508c5c76aab62183/sql/db_test.go#L45-L47

I don't know why "log doesn't work" though. @wangkuiyi Would you mind adding an explanation?

**Review by tonyyang-svail — APPROVED** [review]
